#!/usr/bin/env python3
"""Generate the current bilingual catalog and migration table from structured scope."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = Path("docs/research-baseline/current-catalog.md")


def render(root: Path) -> str:
    def read(path):
        return json.loads((root / path).read_text(encoding="utf-8"))

    baseline = read("config/research-baseline.json")
    topics = {t["topic_id"]: t for t in baseline["topics"]}
    taxonomy = read("config/catalog-taxonomy.json")
    i18n = read("config/publication-i18n.json")["topic_titles_en"]
    migration = read("config/catalog-migration.json")
    codes = {tid: code for c in taxonomy["categories"] for tid, code in c["topic_codes"].items()}
    lines = ["# Current catalog / 現行調査カタログ", "",
             "Generated by `tools/build_catalog_reference.py`; edit the structured sources, not this file.", "",
             f"Catalog revision: {baseline['catalog_revision']}. Active Topics: {len(codes)}. Canonical IDs including history: {len(topics)}.", "",
             "Research scope is not a claim of completed research. / 調査範囲の定義は調査完了を意味しません。", ""]
    for category in taxonomy["categories"]:
        lines += [f"## {category['title_ja']} / {category['title_en']}", ""]
        for tid in sorted(category["topic_ids"], key=codes.get):
            topic = topics[tid]
            lines += [f"### {codes[tid]}: {topic['title_ja']}", "",
                      f"{i18n[tid]}. Canonical ID: `{tid}`. Status: `{topic['status']}`.", "",
                      topic.get("summary_ja", ""), "", topic.get("summary_en", ""), ""]
            for unit in topic.get("research_units", []):
                lines += [f"- `{unit['unit_id']}` **{unit['title_ja']} / {unit['title_en']}** (`{unit['status']}`)",
                          f"  - {unit['question_ja']}", f"  - {unit['question_en']}",
                          f"  - Evidence sections: {', '.join(unit['evidence_section_ids']) or 'none / 未収集'}"]
            related = ", ".join(codes[target] for target in topic.get("related_topic_ids", []))
            lines += ["", f"Related / 関連: {related or 'none'}", ""]
    lines += ["## Migration / 移行対応表", "",
              f"Base commit: `{migration['base_commit']}`. Human Directive: `{migration['human_directive_id']}`.", "",
              "Old display codes are never reused. Original questions remain in `config/catalog-migration.json`.", "",
              "| Previous code / 旧コード | Previous topic / 旧項目 | Current destination / 現在の移管先 |",
              "| --- | --- | --- |"]
    for entry in migration["entries"]:
        targets = [f"{codes[tid]} ({tid})" for tid in entry["target_topic_ids"]]
        targets += [f"`{path}`" for path in entry["target_paths"]]
        lines.append(f"| {entry['source_catalog_code']} | {entry['source_title_ja']} / {entry['source_title_en']} | {'; '.join(targets)} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(ROOT)
    path = ROOT / OUTPUT
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            raise SystemExit("Current catalog reference is stale; run tools/build_catalog_reference.py")
    else:
        path.write_text(expected, encoding="utf-8")
    print(f"Catalog reference {'verified' if args.check else 'generated'}: {OUTPUT}")


if __name__ == "__main__":
    main()
